"""
WhatsApp Sender
"""

import pywhatkit


def send_whatsapp_message(phone_number, email, summary):
    """
    Send AI email summary to WhatsApp.
    """

    message = f"""
🤖 SmartMailNotify

━━━━━━━━━━━━━━━━━━

👤 From:
{email['sender']}

📌 Subject:
{email['subject']}

🤖 Category:
{email['category']}

⭐ Priority:
{email['priority']}

📝 AI Summary:

{summary}

━━━━━━━━━━━━━━━━━━

Generated by SmartMailNotify 🚀
"""

    print("\n📲 Opening WhatsApp...")

    pywhatkit.sendwhatmsg_instantly(
        phone_no=phone_number,
        message=message,
        wait_time=15,
        tab_close=False,
        close_time=5
    )

    print("✅ WhatsApp Message Sent!")